/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SS_aliases.h"
#include "SS.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "DC_aliases.h"
#include "DC.h"
#include "RESET_aliases.h"
#include "RESET.h"
#include "LED_aliases.h"
#include "LED.h"
#include "ADC_DelSig_1.h"
#include "adc_in_aliases.h"
#include "adc_in.h"
#include "adc_threshold_aliases.h"
#include "adc_threshold.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "SW3_aliases.h"
#include "SW3.h"
#include "led_data_aliases.h"
#include "led_data.h"
#include "Clock_1.h"
#include "NP_funcs.h"
#include "SPIM_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "NP_Neo_BITCNT.h"
#include "NP_Neo_ONTime.h"
#include "NP_Neo_OFFTime.h"
#include "NP_Neo_defs.h"
#include "NP_DMA_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

