/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SS_aliases.h"
#include "SS.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "DC_aliases.h"
#include "DC.h"
#include "RESET_aliases.h"
#include "RESET.h"
#include "LED_aliases.h"
#include "LED.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "SW3_aliases.h"
#include "SW3.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "SPIM_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

